### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by hawkeye64** [caddyserver/nginx-adapter#11]
```
$ ./build_caddy.sh 
++ go list -m github.com/caddyserver/caddy/v2
++ cut -d ' ' -f 2
+ CADDY_VERSION=v2.0.0-beta.20
+ mkdir -p caddy
+ cd caddy
+ curl https://raw.githubusercontent.com/caddyserver/caddy/v2/cmd/caddy/main.go
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     16      0 --:--:-- --:--:-- --:--:--    16
+ sed -i.bak 's/^)/	_ "github.com\/caddyserver\/nginx-adapter"\
)/' main.go
+ rm main.go.bak
+ go mod init caddy
go: creating new go.mod: module caddy
+ go mod edit -require=github.com/caddyserver/caddy/v2@v2.0.0-beta.20
+ go build -o caddy_v2
can't load package: package caddy: 
main.go:1:1: expected 'package', found 404
```

I have never used "go" before. This installed on Ubuntu 18.04 using Snap.

**Comment by mholt** [comment]
Ah, the build script needs to be updated to use the master branch instead of v2.

**Comment by hawkeye64** [comment]
Also, your instructions for cloning the repo should include `.git` on the end of the actual repo or it fails

**Comment by mholt** [comment]
@hawkeye64 

> Also, your instructions for cloning the repo should include .git on the end of the actual repo or it fails

Nope, it works without it!

```
$ git clone "https://github.com/caddyserver/nginx-adapter"
Cloning into 'nginx-adapter'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 86 (delta 43), reused 67 (delta 32), pack-reused 0
Unpacking objects: 100% (86/86), done.
```

But perhaps having `.git` is more proper.

**Comment by hawkeye64** [comment]
hmmm, it failed for me. Then I noticed it was missing `.git`, so added it, then it ran. Might depend on your OS, and git for that OS.

**Comment by mohammed90** [comment]
The build script was written before xcaddy existed and when Caddy v2 wasn't on the master branch. I've updated the build instructions to use xcaddy.

Judging by your thread on the forum, the adapter would've been underwhelming for your case 😅  you make heavy use of the `upstream` and `map` directives, which aren't supported yet. The `map` directive should be doable once caddyserver/caddy#3199 is merged.

**Comment by hawkeye64** [comment]
@Mohammed90 Thanks for the info. Yes, we make use of upstream servers a lot, since we are basically in the video camera business (somewhat). It's actually pipeline leak detection with dual cameras (dcam).
