### ISSUE TITLE
Are upstream directives supported?

### ISSUE THREAD

**Issue by scottengle** [caddyserver/nginx-adapter#17]
I'm getting an error with upstream directives:

`[WARNING][nginx] nginx.conf:11: upstream: unrecognized or unsupported nginx directive`

The README suggests that they're supported, but they aren't included in the supported directives under the http context.

Are upstream directives supported?

**Comment by mholt** [comment]
What is your input that is giving you that error?

**Comment by mohammed90** [comment]
Local testing confirmed the bug. I sent the PR to fix it. @scottengle, can you test the PR and double-confirm, please?

**Comment by scottengle** [comment]
It's been a long while since I have done any major development in Go, so take this as you will. I pulled your fix branch and pointed xcaddy to it. It appears to be working as expected. Thanks for the quick turnaround!
