### ISSUE TITLE
Cannot build using xcaddy

### ISSUE THREAD

**Issue by evmcl** [caddyserver/nginx-adapter#24]
System: Ubuntu 22.04 LTS x86_64

Go: 1.18.1

Xcaddy: v0.3.0 h1:3LTHAhHb5YKKqTLLj8kdF9cfGMl4jHV4uRbtw7LBJ6k=

Command: xcaddy build latest --with github.com/caddyserver/nginx-adapter

Errors:
nginx-adapter@v0.0.4/if.go:112:69: cannot use "true" (untyped string constant) as []string value in map literal
nginx-adapter@v0.0.4/if.go:122:75: cannot use roperand (variable of type string) as type []string in map literal

**Comment by mohammed90** [comment]
It wasn't `[]string` until caddyserver/caddy#4433, which was released with v2.5.0 🙂 Hold on, I'll shoot a quick fix momentarily 🏃🏼‍♂️

**Comment by mohammed90** [comment]
Run:
```
xcaddy build --with github.com/caddyserver/nginx-adapter@master
```

**Comment by evmcl** [comment]
Awesome. That did the trick. Thank-you so much.
