### ISSUE TITLE
Is it possible to convert nginx.conf into caddy.json?

### ISSUE THREAD

**Issue by houmie** [caddyserver/nginx-adapter#30]
This is the [nginx file](https://github.com/XTLS/Xray-examples/blob/main/All-in-One-fallbacks-Nginx/nginx.conf) I was hoping to convert.

$ ./caddy adapt --config ~/nginx.conf --adapter nginx
```
{"apps":{"http":{}}}
2023/06/15 11:22:38.832	WARN	nginx	server: unrecognized or unsupported nginx directive	{"file": "/root/nginx.conf", "line": 2}
2023/06/15 11:22:38.832	WARN	nginx	server: unrecognized or unsupported nginx directive	{"file": "/root/nginx.conf", "line": 12}
2023/06/15 11:22:38.832	WARN	nginx	server: unrecognized or unsupported nginx directive	{"file": "/root/nginx.conf", "line": 26}
```

But it seems it's empty. It can't generate it.  Is it because of the warnings?

Many Thanks,

**Comment by mholt** [comment]
I think you're missing the outer `http { }` block.

(Feel free to reopen if that's not the case.)
